import React from 'react';
import {
  Bar,
} from 'react-chartjs-2'
import {
  YearsTableHeader,
  RowHeader,
} from './components/TableComponents'
import {
  ItemTitle
} from './components/ReportComponents'
import { 
  getUnit,
  formatValue,
  fiscalDateYear,
 } from './utils'
import { faMoneyCheckAlt } from '@fortawesome/free-solid-svg-icons'

function RevenueItem({revenueItems}) {
  const [unit, setUnit] = React.useState(null)
  const [pass, setPass] = React.useState(true)

  React.useEffect(() => {
    if (revenueItems && revenueItems[0]) {
      setUnit(getUnit(revenueItems[0].totalRevenue))
      revenueItems.forEach((item) => {
        if (item.totalRevenue < 0 || item.totalRevenueYOY < 0) {
          setPass(false)
        }
      })
    }
  }, [revenueItems])

  const _passFailClass = (value1, value2) => {
    let classColor = 'text-green-600'

    if (value1 < 0 || value2 < 0) {
      classColor = 'text-orange-600'
    }
    return `text-center text-sm py-1 ${classColor}`
  }

  const yearLabels = revenueItems.map((item) => {
    return fiscalDateYear(item.fiscalDate)
  })

  const revenueData = revenueItems.map((item) => {
    return formatValue(item.totalRevenue, unit)
  })

  const revenueYOY = revenueItems.map((item) => {
    return item.totalRevenueYOY
  })

  const revenueChartData = () => {
    return {
      labels: yearLabels,
      datasets: [
        {
          type: 'bar',
          data: revenueData,
          backgroundColor: 'rgba(54, 162, 235, 0.2)',
          borderColor: 'rgba(54, 162, 235, 1)',
          borderWidth: 1,
          barPercentage: .6,
        },
        {
          type: 'line',
          data: revenueData,
          fill: false,
          borderColor: '#718096',
          borderWidth: 1.5,
        },
        {
          label: 'revenue yoy',
          data: revenueYOY,
          hidden: true,
        }
      ],
    }
  }

  const options = {
    tooltips: {
      callbacks: {
        title: function(tooltipItem, data) {
          return data['labels'][tooltipItem[0]['index']];
        },
        label: function(tooltipItem, data) {
          return `Revenue: ${data['datasets'][0]['data'][tooltipItem['index']]} ${unit}`;
        },
        afterLabel: function(tooltipItem, data) {
          let growth = data['datasets'][2]['data'][tooltipItem['index']]
          if (growth) {
            return `YOY Growth: ${data['datasets'][2]['data'][tooltipItem['index']]}%`
          }
        }
      }
    },

    legend: {
      display: false
    },
    scales: {
      yAxes: [
        {
          ticks: {
            beginAtZero: true,
          },
          scaleLabel: {
            display: true,
            labelString: `Revenue (${unit})`
          }
        },
      ],
    },
  }

  const totalRevenueData = () => {
    return revenueItems.map((item, index) => {
      return <td className={_passFailClass(item.totalRevenue, item.totalRevenueYOY ? item.totalRevenueYOY : null)} key={index}>
        {formatValue(item.totalRevenue, unit)}
      </td>
    })
  }

  const totalRevenueYOYData = () => {
    return revenueItems.map((item, index) => {
      return <td className={_passFailClass(item.totalRevenue, item.totalRevenueYOY ? item.totalRevenueYOY : null)} key={index}>
        {item.totalRevenueYOY ? `${item.totalRevenueYOY}%` : ''}
      </td>
    })
  }

  const displayYears = () => {
    return <YearsTableHeader years={revenueItems.map(item => fiscalDateYear(item.fiscalDate))}/>
  }

  const borderColor = pass ? 'border-green-600' : 'border-orange-600'
  
  const revenueTip = <RevenueTip />

  return (
    <div className="w-full md:w-1/2 xl:w-1/3 p-3">
      <div class={`h-full border-b-4 bg-white ${borderColor} rounded-md shadow-lg p-5`}>
        <div className="p-3">
          <ItemTitle
            title='Revenue'
            pass={pass}
            icon={faMoneyCheckAlt}
            tip={revenueTip}
          />
        </div>
        <Bar data={revenueChartData} options={options} />
        <table className="w-full table-auto">
          <tbody>
            <tr>
              <th></th>
              {displayYears()}
            </tr>
            <tr>
              <RowHeader itemName={`Revenue (${unit})`} />
              {totalRevenueData()}
            </tr>
            <tr>
              <RowHeader itemName='YOY Growth' />
              {totalRevenueYOYData()}
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  )
}

function RevenueTip() {
  return (
    <div>
      <div className="text-right font-bold mt-1 mr-1">x</div>
      <div className="font-semibold text-sm ml-1">What is it:</div>
        <div className="text-sm mb-1 ml-1">
          Revenue or sales is the income generated by a company from its business activities.
        </div>
      <div className="font-semibold text-sm ml-1">Why it's important:</div>
        <div className="text-sm mb-1 ml-1">
          It's know as the company's top line, and it's the main reason a company goes into business.
          Stock growth starts with a company making money.
        </div>
      <div className="font-semibold text-sm ml-1">What to look for:</div>
        <div className="text-sm mb-1 ml-1">
          It should be increasing each year so YOY growth values should be positive.
          Double digit growth values are a plus.
        </div>
      <div className="font-semibold text-sm ml-1">What to watch for:</div>
        <div className="text-sm mb-1 ml-1">
          If net income is increasing significantly faster than revenue, it could mean the
          company is cutting costs. This may not be sustainable in the long term.
        </div>
    </div>
  )
}

export default RevenueItem